Header section
Godfrey-Alimony/mobile-portfolio pull request #1
Opened 2022-04-20 13:48 UTC by Godfrey-Alimony

Add Toolbar of the website
Add Headline of the website
Add screenshot of the website.
Add HTML File of the website.
Add CSS File of the website.
Add MIT File of the website.
Add README file of the website.
Add gitignore Folder which ignore node-module.

2022-04-20 18:51 UTC, youmari requested changes
Hi @Godfrey-Alimony, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Nice following the design
✔️ No linters error

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 18:51 UTC, youmari commented on portfolio.html
> +            <div class="Portfolio-flex layout">
Please make sure to wrap your  header section with a `<header>` tag, it's good for semantics proposes and make your HTML  structure make sense

2022-04-20 18:51 UTC, youmari commented on portfolio.html
> +                    </a>
This also should be in a `<nav>` tag because it's the  navigation section of your portfolio and it will make your HTML structure makes sense

2022-04-20 18:51 UTC, youmari commented on portfolio.html
> +                    </div>
- [ ] [optional] try to change this `div` tag to an  `<ul>` tag  and make the `<a>` for each one inside `<li>` tag, it will makes your HTML structure better

2022-04-20 18:51 UTC, youmari commented on portfolio.html
> +                <div class="Portfolio-hero-title-box layout">
Please try to change this `<div>` tag to the `<section>` tag because this part is a headline section so it's better to use the right semantic tag

2022-04-20 18:51 UTC, youmari commented on portfolio.html
> +                <h5 class="Portfolio-highlights3 layout">LET’S CONNECT</h5>
Also, try to change this `h5` tag to `<p>` tag the `<h>`tag headers are only for headers

2022-04-20 18:51 UTC, youmari commented on portfolio.html
> +                        </div>
I suggest wrapping your icons with a `<ul>` tag and each `<a>` tag should be inside an `<li>` tag

2022-04-20 18:51 UTC, youmari commented on portfolio.html
> +    <main class="Portfolio-main layout">
I see some left space at the top of your page, Kindly try to remove it

- [ ] Your design 
![image](https://user-images.githubusercontent.com/61790587/164301420-7cb964ea-078d-4364-8d3c-da39cd485e1d.png)

- [ ] Figma design 

![image](https://user-images.githubusercontent.com/61790587/164301593-0f8d08fc-a10d-46ef-b7f3-fee519a15eb4.png)

2022-04-21 05:18 UTC, Godfrey-Alimony commented on portfolio.html
> +            <div class="Portfolio-flex layout">
Okay I have wrapp it now sir.Thanks alot

2022-04-21 05:20 UTC, Godfrey-Alimony commented on portfolio.html
> +                    </a>
I have corrected it and inserted nav tag.Thanks

2022-04-21 05:29 UTC, Godfrey-Alimony commented on portfolio.html
> +                    </div>
Done.Thank you sir

2022-04-21 05:33 UTC, Godfrey-Alimony commented on portfolio.html
> +                <h5 class="Portfolio-highlights3 layout">LET’S CONNECT</h5>
Done

2022-04-21 05:38 UTC, Godfrey-Alimony commented on portfolio.html
> +                        </div>
done

2022-04-21 06:24 UTC, Godfrey-Alimony commented on portfolio.html
> +    <main class="Portfolio-main layout">
![Screenshot from 2022-04-21 09-22-39](https://user-images.githubusercontent.com/71431803/164387672-a51f537d-c753-4ac6-8ba1-610ac661068c.png)
Done

2022-04-21 06:30 UTC, Godfrey-Alimony commented
I have corrected all you told me to do sir.Thanks

2022-04-21 06:57 UTC, Godfrey-Alimony commented
Dear sir,
I have corrected all what you told me to do and i have submited it for your review agian.Thans

2022-04-21 07:03 UTC, youmari commented
> Dear sir, I have corrected all what you told me to do and i have submited it for your review agian.Thans

@Godfrey-Alimony  yes bro submit again for a review

2022-04-21 07:37 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @Godfrey-Alimony,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * I kindly suggest that you include a title at the top of  your PR Description and study the [Professional Repo rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to know how to create a title in your Pull Request.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-21 07:37 UTC, topeogunleye commented on portfolio.html
> +                </div>
- [ ] [REQUIRED] As the previous reviewer suggested, the following code should be wrapped in a `section` tag and I think it does not need to be in the `header` tag.

2022-04-21 07:37 UTC, topeogunleye commented on portfolio.html
> +                    </div>
- [ ] Great Job implementing the `ul` and `li` as the previous reviewer suggested, but you do not need to create a `div` and `ul` for each icon. You can achieve the same result with the following code:

### EXAMPLE
```
 <ul class="Portfolio-icon layout">
                            <li><a href="#" class="fa fa-twitter"></a></li>
                            <li><a href="#" class="fa fa-facebook-f"></a></li>
                            <li><a href="#" class="fa fa-linkedin"></a></li>
                            <li><a href="#" class="fa fa-github"></a></li>
                            <li><a href="#" class="fa fa-angellist"></a></li>
                        </ul>
```

Then apply display flex and adjust the width to make the media icons align horizontally

2022-04-21 09:14 UTC, Godfrey-Alimony commented on portfolio.html
> +                </div>
I have wrape it sir.

2022-04-21 09:16 UTC, Godfrey-Alimony commented on portfolio.html
> +                    </div>
Done

2022-04-21 09:52 UTC, topeogunleye commented on portfolio.html
> +                </div>
Great. I kindly suggest that you submit for review again

2022-04-21 09:53 UTC, topeogunleye commented on portfolio.html
> +                    </div>
Great :+1:

2022-04-21 11:14 UTC, Godfrey-Alimony commented on portfolio.html
> +                <div class="Portfolio-hero-title-box layout">
done

2022-04-21 16:46 UTC, zieeco requested changes
Hi @Godfrey-Alimony 

<img src="https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter error :100: 
- Nice design :100: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Check the comments under the review._

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 16:46 UTC, zieeco commented on portfolio.html
> +            <main-cover class="Portfolio-flex layout">
- [ ]  **[REQUIRED CHANGES]**

Great job on implementing the changes by the previous reviewers but I can see that you don't really seem to understand what was asked of you by the reviewers. I will try explaining more in detail here below:
- Your tag `<main-cover>` is not a HTML semantic tag. it would have been better if you used a `<div> tag` because you used it as a wrapper to wrap your `<header>` and your `<section-headlie>` of which the `<section-headline> is not a Html5 semantic tag also`.

2022-04-21 16:46 UTC, zieeco commented on portfolio.html
> +                </header>
- [ ] **[OPTIONAL]**
- Your header tag should not be a child of the main as used in your website, Although, there are many ways to interpret semantics, It's highly recommended to use headers as separated elements not within the main tag, but in between.
[check here for more](https://stackoverflow.com/questions/20470345/should-the-header-and-footer-tags-be-inside-the-main-tag#:~:text=Rule%20of%20thumb%20%3A,)%20in%20your%20.)

2022-04-21 16:46 UTC, zieeco commented on portfolio.html
> +                <section-headline>
- [ ] **[REQUIRED CHANGES]**

I could see how much you tried implementing the changes which are great but also I see you don't really understand how to implement it...
- Your `<section-headline> tag` was wrongly implement. It is supposed to be a `<section> tag` with a class of `headline` [optionally]. And, I think that's where you got confused.
 Please, kindly read more about the htm5 semantic tag [here](https://www.w3schools.com/html/html5_semantic_elements.asp) to get a better understanding of them.

2022-04-22 08:53 UTC, phelian23 approved these changes
Hi @Godfrey-Alimony, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 07:18 UTC, merged