Mobile-portfolio-Headline section
Godfrey-Alimony/Mobile-Portfolio pull request #1
Opened 2022-05-25 12:51 UTC by Godfrey-Alimony

Add markup for the Mobile portfolio website.
Add stying css file for the Mobile portfolio website.
Add  App-screenshot for the Mobile portfolio website.
Add README File for the Mobile portfolio website.
Add MIT File for the Mobile portfolio website.
Add Image Folder of the Mobile portfolio website

2022-05-25 13:53 UTC, vechicin requested changes
# Hi @Godfrey-Alimony  ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good PR title/description
- [x] Correct GitHub Flow use
- [x] Good commit history
- [x] Linters checks passing

## Required Changes ♻️

- [ ] Your design, although very similar to the template, is lacking some important details. I think this is due to the fact you're using a lot of `position: relative` to render the layout. I recommend you try to refactor your code so you can position the elements on the page using flexbox **exclusively** as it is a project requirement.

<img width="234" alt="Screen Shot 2022-05-25 at 8 50 11" src="https://user-images.githubusercontent.com/82426682/170278287-dd2caf0a-1175-4d2c-b94f-e49360241784.png">

Here's your design: 
<img width="202" alt="Screen Shot 2022-05-25 at 8 50 59" src="https://user-images.githubusercontent.com/82426682/170278466-e177c0b8-9f83-4543-a5c2-2517a26303da.png">

Here's the template design (I apologize for your colleague's pointers):
<img width="185" alt="Screen Shot 2022-05-25 at 8 52 36" src="https://user-images.githubusercontent.com/82426682/170278850-f62e0ed0-5a2a-4188-8678-1fdbc95ffb07.png">


_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 13:53 UTC, vechicin commented on styles.css
> +}
I couldn't find the corresponding tag with this class in your HTML file. Kindly remove any unused classes to keep your code clean and organized.

2022-05-25 13:53 UTC, vechicin commented on portfolio.html
> +            </h2>
According to the evaluation guidelines, this section should be wrapped with a `p` tag.

<img width="333" alt="Screen Shot 2022-05-25 at 8 38 23" src="https://user-images.githubusercontent.com/82426682/170275760-56067caf-8a0e-488f-8dca-3095411d0deb.png">

Kindly fix this.

2022-05-25 13:55 UTC, vechicin commented
https://github.com/Godfrey-Alimony/Mobile-Portfolio/blob/a0bbb79f71d8c085a42910aee2cd58acfc492761/README.md?plain=1#L17-L52
[OPTIONAL] I recommend you add instructions on how to get a local copy of this project and how to install the necessary dependencies for it to run properly, it'll make your repo look more professional.

2022-05-25 13:58 UTC, vechicin commented
https://github.com/Godfrey-Alimony/Mobile-Portfolio/blob/a0bbb79f71d8c085a42910aee2cd58acfc492761/README.md?plain=1#L54-L59
Be careful with the way you're linking your social media accounts. Kindly fix this as it makes your project look a little unprofessional. The markup for it goes like this: [your_social_media_handle] (link_to_social_media_profile). You need to remove the space between the bracket and the parenthesis for the link to work, I had to add it so you can see how the markup looks like.

2022-05-25 14:35 UTC, Godfrey-Alimony commented on styles.css
> +}
Done

2022-05-25 14:37 UTC, Godfrey-Alimony commented on portfolio.html
> +            </h2>
Done

2022-05-25 15:10 UTC, Godfrey-Alimony commented
> https://github.com/Godfrey-Alimony/Mobile-Portfolio/blob/a0bbb79f71d8c085a42910aee2cd58acfc492761/README.md?plain=1#L54-L59
> 
> 
> Be careful with the way you're linking your social media accounts. Kindly fix this as it makes your project look a little unprofessional. The markup for it goes like this: [your_social_media_handle] (link_to_social_media_profile). You need to remove the space between the bracket and the parenthesis for the link to work, I had to add it so you can see how the markup looks like.

Done

2022-05-25 16:29 UTC, Godfrey-Alimony commented
Thank you much sir.

2022-05-25 16:29 UTC, merged

2022-05-26 05:16 UTC, Godfrey-Alimony commented
Thank you so much Sir.

On Wed, May 25, 2022 at 7:25 PM Olipliche B.F. Mavoungou Paka <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @Godfrey-Alimony <https://github.com/Godfrey-Alimony> ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Godfrey-Alimony/Mobile-Portfolio/pull/1#pullrequestreview-985128267>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARA7M65QICYRJX4ORPHPIFTVLZH6ZANCNFSM5W5A4RKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>